version: "3.8"

services:
  database:
    container_name: rbltdjango_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=
      - POSTGRES_PASSWORD=rbltdjango
      - POSTGRES_USER=rbltdjango
    ports:
      - "5434:5432"
