name: rblt-django

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Instalar dependências
        run: |
          pip install -q pipenv codecov
          pipenv sync --dev
          cp contrib/env-sample .env
      - name: Lint com flake8
        run: |
          pipenv run flake8
      - name: Teste de código com pytest
        run: |
          pytest rblt-django --cov=rblt-django
      - name: Cobertura de testes com codecov
        env:
            CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: |
            codecov -t CODECOV_TOKEN